[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Bu redirect kuralı SPA (Tek Sayfalı Uygulama) yönlendirmesi için gerekli
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API fonksiyonları için yönlendirme
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# === YENİ VE EN ÖNEMLİ BÖLÜM ===
# Bu kural, tüm sayfalara bir Cross-Origin-Opener-Policy başlığı ekler.
# Bu, Firebase Auth popup'ının ana pencereyle iletişim kurmasına izin verir.
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
